name: Lenora Helm Online
favicon: null
layout_spectrum: 0.6995643984992057
typography_spectrum: 0.13872795971110463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9827030582819134
  lightness: 0.8524222485721111
  saturation: 0.48969134339131415
  rhythmicContrast: 0.2527466472238302
purpose: []
