name: Lenora Helm Online
favicon: null
layout_spectrum: 0.99063
typography_spectrum: 0.13872795971110463
title: Vocal Jazz Musician
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#c0c0c0'
    - '#929292'
    - '#583434'
    - '#ff6e62'
  brandStrength: 0.75
  lightness: 0.8524222485721111
  saturation: 0.48969134339131415
  rhythmicContrast: 0.2527466472238302
purpose: []
